version: '3'
services:
  pubsub:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    ports:
      - "8085:8085"
    command: gcloud beta emulators pubsub start --project=iata-teletype-project --host-port=0.0.0.0:8085
